USE easypass;
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('auletta@unisa.it', 'Vincenzo', 'AULETTA', 'a', 'DIEM');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('cpinto@unisa.it', 'Carmine', 'PINTO ', 'a', 'DIPSUM');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('cvecchione@unisa.it', 'Carmine', 'VECCHIONE', 'a', 'DIPMED');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('destefanis@unisa.it', 'Sergio Pietro', 'DESTEFANIS', 'a', 'DISES');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('g.rizanno@unisa.it', 'Gianvittorio', 'RIZZANO', 'a', 'DICIV');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('gsciancalepore@unisa.it', 'Giovanni', 'SCIANCALEPORE', 'a', 'Giurisprudenza');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('iorio@unisa.it', 'Gennaro', 'IORIO', 'a', 'DISPS');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('lcerchiai@unisa.it', 'Luca', 'CERCHIAI', 'a', 'DISPAC');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('lgargano@unisa.it', 'Luisa', 'GARGANO', 'a', 'DI');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('paiello@unisa.it', 'Paola', 'AIELLO', 'a', 'DISUFF');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('parente@unisa.it', 'Domenico', 'PARENTE', 'a', 'DISA-MIS');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('pcampiglia@unisa.it', 'Pietro', 'CAMPIGLIA ', 'a', 'DIFARMA');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('plongo@unisa.it', 'Pasquale', 'LONGO', 'a', 'DCB');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('raffaele@unisa.it', 'Raffaele', 'CERULLI', 'a', 'DIPMAT');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('rpantani@unisa.it', 'Roberto', 'PANTANI', 'a', 'DIIN');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('sdepasquale@unisa.it', 'Salvatore', 'DE PASQUALE', 'a', 'DF');
INSERT INTO easypass.direttore (Username_Dir, Nome_Dir, Cognome_Dir, Password_Dir, Codice_Dip) VALUES ('vdantonio@unisa.it', 'Virgilio', 'D''ANTONIO', 'a', 'DISPC');
