USE easypass;
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DCB', 'Chimica e Biologia "Adolfo Zambelli"', 'DCB');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DF', 'Fisica "E.R.Caianiello"', 'DF');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DI', 'Informatica', 'DI');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DICIV', 'Ingegneria Civile', 'DICIV');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIEM', 'Ingegneria dell''Informazione ed Elettrica e Matematica applicata', 'DIEM');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIFARMA', 'Farmacia', 'DIFAR');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIIN', 'Ingegneria Industriale', 'DIIN');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIPMAT', 'Matematica', 'DIPMA');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIPMED', 'Medicina, Chirurgia e Odontoiatria "Scuola Medica Salernitana"', 'DIPME');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIPSUM', 'Studi Umanistici', 'DIPSU');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISA-MIS', 'Scienze Aziendali - Management & Innovation Systems', 'DISA-MIS');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISES', 'Scienze Economiche e Statistiche', 'DISES');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISPAC', 'Scienze del Patrimonio Culturale', 'DISPA');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISPC', 'Scienze Politiche e della Comunicazione', 'DISPC');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISPS', 'Studi Politici e Sociali', 'DISPS');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISUFF', 'Scienze Umane, Filosofiche e della Formazione', 'DISUF');
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DSG', 'Scienze Giuridiche (Scuola di Giurisprudenza)', 'DSG');
