USE easypass;
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DCB', 0, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DF', 1, 0, 0, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DI', 1, 1, 1, 1, 1);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DICIV', 0, 1, 1, 1, 1);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DIEM', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DIFAR', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DIIN', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DIPMA', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DIPME', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DIPSU', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DISA-MIS', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DISES', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DISPA', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DISPC', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DISPS', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DISUF', 1, 1, 1, 0, 0);
INSERT INTO easypass.formato (ID_formato, N_studenti, GP_validi, GP_nonValidi, Nome_Cognome, Ddn) VALUES ('DSG', 1, 1, 1, 0, 0);
