USE easypass;
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DCB', 'Chimica e Biologia "Adolfo Zambelli"', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DF', 'Fisica "E.R.Caianiello"', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DI', 'Informatica', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DICIV', 'Ingegneria Civile', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIEM', 'Ingegneria dell''Informazione ed Elettrica e Matematica applicata', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIFARMA', 'Farmacia', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIIN', 'Ingegneria Industriale', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIPMAT', 'Matematica', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIPMED', 'Medicina, Chirurgia e Odontoiatria “Scuola Medica Salernitana”', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DIPSUM', 'Studi Umanistici', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISA-MIS', 'Scienze Aziendali - Management & Innovation Systems', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISES', 'Scienze Economiche e Statistiche', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISPAC', 'Scienze del Patrimonio Culturale', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISPC', 'Scienze Politiche e della Comunicazione', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISPS', 'Studi Politici e Sociali', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DISUFF', 'Scienze Umane, Filosofiche e della Formazione', 5);
INSERT INTO easypass.dipartimento (Codice_Dip, Nome, ID_formato) VALUES ('DSG', 'Scienze Giuridiche (Scuola di Giurisprudenza)', 5);
